// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/catalogapi/catalog.proto

/*
Package catalogapi is a generated protocol buffer package.

It is generated from these files:
	pkg/catalogapi/catalog.proto

It has these top-level messages:
	PutRequest
	PutResponse
	SearchRequest
	SearchResponse
	Publication
	Date
*/
package catalogapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PutRequest struct {
	Pub *Publication `protobuf:"bytes,1,opt,name=pub" json:"pub,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PutRequest) GetPub() *Publication {
	if m != nil {
		return m.Pub
	}
	return nil
}

type PutResponse struct {
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SearchRequest struct {
	AuthorPublicKey   []byte `protobuf:"bytes,1,opt,name=author_public_key,json=authorPublicKey,proto3" json:"author_public_key,omitempty"`
	ReaderPublicKey   []byte `protobuf:"bytes,2,opt,name=reader_public_key,json=readerPublicKey,proto3" json:"reader_public_key,omitempty"`
	ReceivedDateStart *Date  `protobuf:"bytes,3,opt,name=received_date_start,json=receivedDateStart" json:"received_date_start,omitempty"`
	ReceivedDateEnd   *Date  `protobuf:"bytes,4,opt,name=received_date_end,json=receivedDateEnd" json:"received_date_end,omitempty"`
	Limit             int32  `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SearchRequest) GetAuthorPublicKey() []byte {
	if m != nil {
		return m.AuthorPublicKey
	}
	return nil
}

func (m *SearchRequest) GetReaderPublicKey() []byte {
	if m != nil {
		return m.ReaderPublicKey
	}
	return nil
}

func (m *SearchRequest) GetReceivedDateStart() *Date {
	if m != nil {
		return m.ReceivedDateStart
	}
	return nil
}

func (m *SearchRequest) GetReceivedDateEnd() *Date {
	if m != nil {
		return m.ReceivedDateEnd
	}
	return nil
}

func (m *SearchRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type SearchResponse struct {
	Pubs      []*Publication `protobuf:"bytes,1,rep,name=pubs" json:"pubs,omitempty"`
	UntilDate *Date          `protobuf:"bytes,2,opt,name=until_date,json=untilDate" json:"until_date,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SearchResponse) GetPubs() []*Publication {
	if m != nil {
		return m.Pubs
	}
	return nil
}

func (m *SearchResponse) GetUntilDate() *Date {
	if m != nil {
		return m.UntilDate
	}
	return nil
}

// Publication is a libri publication plus a receipt time, intentionally defined separately to
// give us the flexibility down the road to add things to one and not the other.
type Publication struct {
	EnvelopeKey     []byte `protobuf:"bytes,1,opt,name=envelope_key,json=envelopeKey,proto3" json:"envelope_key,omitempty"`
	EntryKey        []byte `protobuf:"bytes,2,opt,name=entry_key,json=entryKey,proto3" json:"entry_key,omitempty"`
	AuthorPublicKey []byte `protobuf:"bytes,3,opt,name=author_public_key,json=authorPublicKey,proto3" json:"author_public_key,omitempty"`
	ReaderPublicKey []byte `protobuf:"bytes,4,opt,name=reader_public_key,json=readerPublicKey,proto3" json:"reader_public_key,omitempty"`
	ReceievedTime   int64  `protobuf:"varint,5,opt,name=receieved_time,json=receievedTime" json:"receieved_time,omitempty"`
}

func (m *Publication) Reset()                    { *m = Publication{} }
func (m *Publication) String() string            { return proto.CompactTextString(m) }
func (*Publication) ProtoMessage()               {}
func (*Publication) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Publication) GetEnvelopeKey() []byte {
	if m != nil {
		return m.EnvelopeKey
	}
	return nil
}

func (m *Publication) GetEntryKey() []byte {
	if m != nil {
		return m.EntryKey
	}
	return nil
}

func (m *Publication) GetAuthorPublicKey() []byte {
	if m != nil {
		return m.AuthorPublicKey
	}
	return nil
}

func (m *Publication) GetReaderPublicKey() []byte {
	if m != nil {
		return m.ReaderPublicKey
	}
	return nil
}

func (m *Publication) GetReceievedTime() int64 {
	if m != nil {
		return m.ReceievedTime
	}
	return 0
}

type Date struct {
	Year  int32 `protobuf:"varint,1,opt,name=year" json:"year,omitempty"`
	Month int32 `protobuf:"varint,2,opt,name=month" json:"month,omitempty"`
	Day   int32 `protobuf:"varint,3,opt,name=day" json:"day,omitempty"`
}

func (m *Date) Reset()                    { *m = Date{} }
func (m *Date) String() string            { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()               {}
func (*Date) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func init() {
	proto.RegisterType((*PutRequest)(nil), "catalogapi.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "catalogapi.PutResponse")
	proto.RegisterType((*SearchRequest)(nil), "catalogapi.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "catalogapi.SearchResponse")
	proto.RegisterType((*Publication)(nil), "catalogapi.Publication")
	proto.RegisterType((*Date)(nil), "catalogapi.Date")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Catalog service

type CatalogClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type catalogClient struct {
	cc *grpc.ClientConn
}

func NewCatalogClient(cc *grpc.ClientConn) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/catalogapi.Catalog/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/catalogapi.Catalog/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Catalog service

type CatalogServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterCatalogServer(s *grpc.Server, srv CatalogServer) {
	s.RegisterService(&_Catalog_serviceDesc, srv)
}

func _Catalog_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogapi.Catalog/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogapi.Catalog/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Catalog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "catalogapi.Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Catalog_Put_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Catalog_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/catalogapi/catalog.proto",
}

func init() { proto.RegisterFile("pkg/catalogapi/catalog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0x59, 0x76, 0xb7, 0xd0, 0x49, 0xd3, 0x36, 0x06, 0xd1, 0x25, 0x70, 0x08, 0x2b, 0x21,
	0x15, 0x90, 0x52, 0xa9, 0x1c, 0xe0, 0xc0, 0x81, 0xbf, 0x27, 0x2e, 0x91, 0xcb, 0x3d, 0x72, 0xb2,
	0xa3, 0xc6, 0xea, 0xc6, 0x36, 0xde, 0x71, 0xa5, 0xbc, 0x00, 0x4f, 0xc7, 0x2b, 0x21, 0x21, 0xdb,
	0xdd, 0x66, 0xa3, 0x04, 0xa4, 0xde, 0xc6, 0x33, 0xdf, 0x8c, 0x3e, 0xff, 0xc6, 0x86, 0xe7, 0xe6,
	0xea, 0xf2, 0x6c, 0x2e, 0x48, 0xd4, 0xfa, 0x52, 0x18, 0xd9, 0x86, 0x63, 0x63, 0x35, 0x69, 0x06,
	0xeb, 0x4a, 0xf9, 0x0e, 0x60, 0xe2, 0x88, 0xe3, 0x4f, 0x87, 0x0d, 0xb1, 0x57, 0x90, 0x1a, 0x37,
	0x2b, 0x92, 0x51, 0x72, 0xda, 0x3b, 0x3f, 0x19, 0xaf, 0x75, 0xe3, 0x89, 0x9b, 0xd5, 0x72, 0x2e,
	0x48, 0x6a, 0xc5, 0xbd, 0xa6, 0xec, 0x43, 0x2f, 0x34, 0x36, 0x46, 0xab, 0x06, 0xcb, 0x3f, 0x09,
	0xf4, 0x2f, 0x50, 0xd8, 0xf9, 0xa2, 0x9d, 0xf5, 0x1a, 0x06, 0xc2, 0xd1, 0x42, 0xdb, 0xa9, 0x09,
	0xbd, 0xd3, 0x2b, 0x5c, 0x85, 0xc9, 0x07, 0xfc, 0x28, 0x16, 0xe2, 0xcc, 0xef, 0xb8, 0xf2, 0x5a,
	0x8b, 0xa2, 0xc2, 0x0d, 0xed, 0xfd, 0xa8, 0x8d, 0x85, 0xb5, 0xf6, 0x23, 0x3c, 0xb2, 0x38, 0x47,
	0x79, 0x8d, 0xd5, 0xb4, 0x12, 0x84, 0xd3, 0x86, 0x84, 0xa5, 0x22, 0x0d, 0x9e, 0x8f, 0xbb, 0x9e,
	0xbf, 0x0a, 0x42, 0x3e, 0x68, 0xc5, 0xfe, 0x74, 0xe1, 0xa5, 0xec, 0x03, 0x0c, 0x36, 0x27, 0xa0,
	0xaa, 0x8a, 0xec, 0x1f, 0xfd, 0x47, 0xdd, 0xfe, 0x6f, 0xaa, 0x62, 0x8f, 0x21, 0xaf, 0xe5, 0x52,
	0x52, 0x91, 0x8f, 0x92, 0xd3, 0x9c, 0xc7, 0x43, 0xa9, 0xe0, 0xb0, 0xbd, 0x7e, 0x24, 0xc2, 0xde,
	0x40, 0x66, 0xdc, 0xac, 0x29, 0x92, 0x51, 0xfa, 0x3f, 0x98, 0x41, 0xc4, 0xce, 0x00, 0x9c, 0x22,
	0x59, 0x07, 0x3f, 0xe1, 0xe6, 0xbb, 0xbc, 0xec, 0x07, 0x8d, 0x0f, 0xcb, 0xdf, 0x89, 0xe7, 0x7f,
	0x3b, 0x86, 0xbd, 0x80, 0x03, 0x54, 0xd7, 0x58, 0x6b, 0x83, 0x1d, 0xd0, 0xbd, 0x36, 0xe7, 0xc1,
	0x3d, 0x83, 0x7d, 0x54, 0x64, 0x57, 0x1d, 0xb8, 0x0f, 0x43, 0xe2, 0x66, 0x03, 0xdb, 0xdb, 0x4a,
	0xef, 0xb0, 0xad, 0x6c, 0xf7, 0xb6, 0x5e, 0xc2, 0x61, 0x00, 0x88, 0x1e, 0x36, 0xc9, 0x25, 0x06,
	0x6c, 0x29, 0xef, 0xdf, 0x66, 0x7f, 0xc8, 0x25, 0x96, 0x9f, 0x21, 0xf3, 0xd7, 0x62, 0x0c, 0xb2,
	0x15, 0x0a, 0x1b, 0xec, 0xe7, 0x3c, 0xc4, 0x1e, 0xf8, 0x52, 0x2b, 0x5a, 0x04, 0xcf, 0x39, 0x8f,
	0x07, 0x76, 0x0c, 0x69, 0x25, 0xa2, 0xc5, 0x9c, 0xfb, 0xf0, 0xfc, 0x57, 0x02, 0x0f, 0xbe, 0x44,
	0x62, 0xec, 0x3d, 0xa4, 0x13, 0x47, 0xec, 0xc9, 0x26, 0xf5, 0xf6, 0x9d, 0x0f, 0x4f, 0xb6, 0xf2,
	0x37, 0xcf, 0xf8, 0x1e, 0xfb, 0x04, 0x7b, 0x71, 0x91, 0xec, 0x69, 0x57, 0xb4, 0xf1, 0xb6, 0x87,
	0xc3, 0x5d, 0xa5, 0x76, 0xc4, 0x6c, 0x2f, 0x7c, 0xb3, 0xb7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xbc, 0xd8, 0x4f, 0x23, 0x86, 0x03, 0x00, 0x00,
}
