version: 2
jobs:
  build:
    docker:
      - image: gcr.io/elxir-core-infra/service-base-build:latest
        auth:
          username: _json_key
          password: ${GCR_SVC_JSON}
    parallelism: 1
    working_directory: /go/src/github.com/elixirhealth/catalog
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - arch={{ arch }}-vendor={{ checksum "Gopkg.lock" }}-v1
            - arch={{ arch }}-vendor={{ checksum "Gopkg.lock" }}
            - arch={{ arch }}
      - run: make get-deps
      - save_cache:
          key: arch={{ arch }}-vendor={{ checksum "Gopkg.lock" }}-v1
          paths:
            - vendor
      - run: make build
      - run: make build-static
      - run: make docker-image
      - run: make test
      - run: make lint
      - run: make acceptance
      - run: make demo
      - run:
          name: publish docker image
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              docker login -u _json_key -p "${GCR_SVC_JSON}" gcr.io
              CATALOG_VERSION=$(./deploy/bin/catalog version)
              docker tag gcr.io/elxir-core-infra/catalog:snapshot gcr.io/elxir-core-infra/catalog:${CATALOG_VERSION}
              docker tag gcr.io/elxir-core-infra/catalog:snapshot gcr.io/elxir-core-infra/catalog:latest
              docker push gcr.io/elxir-core-infra/catalog:${CATALOG_VERSION}
              docker push gcr.io/elxir-core-infra/catalog:latest
            elif [[ "${CIRCLE_BRANCH}" == "develop" ]]; then
              docker login -u _json_key -p "${GCR_SVC_JSON}" gcr.io
              docker push gcr.io/elxir-core-infra/catalog:snapshot
            fi
